apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-zvcc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-zvcc
    app.kubernetes.io/part-of: build-suite-test-application-qfkx
  name: test-component-pac-zvcc
  namespace: build-e2e-ogqd-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-zvcc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-zvcc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:e7f0ecd25c7f16766c327e85da814d8083a63baa1a8ad436592cbe27f46fc5a2
        imagePullPolicy: Always
        name: container-image
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
