apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-component-pac-zvcc
  namespace: build-e2e-ogqd-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:e7f0ecd25c7f16766c327e85da814d8083a63baa1a8ad436592cbe27f46fc5a2
        name: container-image
        resources: {}
status: {}
